### ISSUE TITLE
Initialize in every activity?

### ISSUE THREAD

**Issue by nicemak** [AmanpreetYatin/Easy-SharedPreferences#1]
thanks for great library, i have a question does we need to initialize it in every activity? like put this code

`EasySharedPreferenceConfig.initDefault(EasySharedPreferenceConfig.Builder() .inputFileName("easy_preference") .inputMode(Context.MODE_PRIVATE) .build())`

in every activity?

**Comment by AmanpreetYatin** [comment]
no you don't need to initialize it in every activity.
